# Generated by Django 3.2.15 on 2022-09-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=False, max_length=36, unique=True),
        ),
    ]
